### ISSUE TITLE
Uninstall is not working

### ISSUE THREAD

**Issue by camilamacedo86** [integr8ly/installation#259] opened 2018-12-11 14:04 UTC
## Description
Uninstall is not working

## Expected Behavior
The uninstall finish with success and all that was installed by the installer be removed.
 
## Actual Behavior
```shell
FAILED - RETRYING: Wait for keycloak resources to be removed (1 retries left).
fatal: [127.0.0.1]: FAILED! => {"attempts": 50, "changed": false, "cmd": "oc get keycloak rhsso -n sso", "delta": "0:00:00.146557", "end": "2018-12-11 10:22:22.512974", "failed": true, "failed_when_result": true, "rc": 0, "start": "2018-12-11 10:22:22.366417", "stderr": "", "stderr_lines": [], "stdout": "NAME      AGE\nrhsso     11h", "stdout_lines": ["NAME      AGE", "rhsso     11h"]}

PLAY RECAP ******************************************************************************************************************************************************
127.0.0.1                  : ok=27   changed=12   unreachable=0    failed=1  
```
## Environment

* Operating system: RHEL / RHDPS
* OpenShift version: 
```shell
$ oc version
oc v3.10.14
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
```
* Ansible version:
```shell
$ ansible --version
[WARNING]: log file at /root/ansible.log is not writeable and we cannot create it, aborting

ansible 2.4.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
* Project Version/Tag: master https://github.com/integr8ly/installation/commit/87af58338d1801c40408b821bd562a1568284945

## Steps to reproduce

1. Create an instance in RHPDS. See [here](https://github.com/integr8ly/installation#using-red-hat-product-demo-system-to-have-an-openshift-instance-valid-just-for-partners-and-redhatters)
2. Following the steps to install and run the installer with the launcher variables ( `ansible-playbook -i inventories/hosts playbooks/install.yml -e github_client_id=X -e github_client_secret=X` ). See [here](https://github.com/integr8ly/installation#installing-from-rhpds)
**IMPORTANT:** The GitHub OAuth app was updated as described in the steps of the README. See [here](https://github.com/integr8ly/installation#411-create-github-oauth-to-enable-github-authorization-for-launcher)
3. Run the uninstall. ( ansible-playbook -i inventories/hosts playbooks/uninstall.yml )

**Comment by trepel** [comment] 2019-01-04 16:20
Hi @camilamacedo86 , closing this one. I cannot reproduce it now. We run uninstalls nightly (see the two jobs in https://integreatly-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Nightly/). If you still experience an issue, please reopen (or for better visibility use jira INTLY project instead - https://issues.jboss.org/projects/INTLY/summary)

**Closed by trepel** 2019-01-04 16:20 UTC
Labels: bug, p1
