### ISSUE TITLE
Installation fails in TASK [launcher : Generate Launcher SSO auth token for admin user] 

### ISSUE THREAD

**Issue by tremes** [integr8ly/installation#177] opened 2018-11-21 14:14 UTC
## Description
Installation (currently installing from master - f26656022a0206e80a2095d5f4a36acaa6c7c8a8) fails with:
```
fatal: [127.0.0.1]: FAILED! => {"attempts": 60, "cache_control": "private, max-age=0, no-cache, no-store", "changed": false, "connection": "close", "content": "<html>\n  <head>\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\n  <style type=\"text/css\">\n  /*!\n   * Bootstrap v3.3.5 (http://getbootstrap.com)\n   * Copyright 2011-2015 Twitter, Inc.\n   * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)\n   */\n  /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */\n  html {\n    font-family: sans-serif;\n    -ms-text-size-adjust: 100%;\n    -webkit-text-size-adjust: 100%;\n  }\n  body {\n    margin: 0;\n  }\n  h1 {\n    font-size: 1.7em;\n    font-weight: 400;\n    line-height: 1.3;\n    margin: 0.68em 0;\n  }\n  * {\n    -webkit-box-sizing: border-box;\n    -moz-box-sizing: border-box;\n    box-sizing: border-box;\n  }\n  *:before,\n  *:after {\n    -webkit-box-sizing: border-box;\n    -moz-box-sizing: border-box;\n    box-sizing: border-box;\n  }\n  html {\n    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);\n  }\n  body {\n    font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n    line-height: 1.66666667;\n    font-size: 13px;\n    color: #333333;\n    background-color: #ffffff;\n    margin: 2em 1em;\n  }\n  p {\n    margin: 0 0 10px;\n    font-size: 13px;\n  }\n  .alert.alert-info {\n    padding: 15px;\n    margin-bottom: 20px;\n    border: 1px solid transparent;\n    background-color: #f5f5f5;\n    border-color: #8b8d8f;\n    color: #363636;\n    margin-top: 30px;\n  }\n  .alert p {\n    padding-left: 35px;\n  }\n  a {\n    color: #0088ce;\n  }\n\n  ul {\n    position: relative;\n    padding-left: 51px;\n  }\n  p.info {\n    position: relative;\n    font-size: 15px;\n    margin-bottom: 10px;\n  }\n  p.info:before, p.info:after {\n    content: \"\";\n    position: absolute;\n    top: 9%;\n    left: 0;\n  }\n  p.info:before {\n    content: \"i\";\n    left: 3px;\n    width: 20px;\n    height: 20px;\n    font-family: serif;\n    font-size: 15px;\n    font-weight: bold;\n    line-height: 21px;\n    text-align: center;\n    color: #fff;\n    background: #4d5258;\n    border-radius: 16px;\n  }\n\n  @media (min-width: 768px) {\n    body {\n      margin: 4em 3em;\n    }\n    h1 {\n      font-size: 2.15em;}\n  }\n\n  </style>\n  </head>\n  <body>\n    <div>\n      <h1>Application is not available</h1>\n      <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>\n\n      <div class=\"alert alert-info\">\n        <p class=\"info\">\n          Possible reasons you are seeing this page:\n        </p>\n        <ul>\n          <li>\n            <strong>The host doesn't exist.</strong>\n            Make sure the hostname was typed correctly and that a route matching this hostname exists.\n          </li>\n          <li>\n            <strong>The host exists, but doesn't have a matching path.</strong>\n            Check if the URL path was typed correctly and that the route was created using the desired path.\n          </li>\n          <li>\n            <strong>Route and path matches, but all pods are down.</strong>\n            Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.\n          </li>\n        </ul>\n      </div>\n    </div>\n  </body>\n</html>\n", "content_type": "text/html", "msg": "Status code was 503 and not [200]: HTTP Error 503: Service Unavailable
```
## Expected Behavior
Installation works:-)

## Actual Behavior
Pods in launcher namespace look OK. But psql log might point to some issue:
```
The  files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/pgsql/data/userdata ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
creating template1 database in /var/lib/pgsql/data/userdata/base/1 ... ok
initializing pg_authid ... ok
initializing dependencies ... ok
creating system views ... ok
loading system objects' descriptions ... ok
creating collations ... ok
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
creating information schema ... ok
loading PL/pgSQL server-side language ... ok
vacuuming database template1 ... ok
copying template1 to template0 ... ok
copying template1 to postgres ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/pgsql/data/userdata -l logfile start


WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
waiting for server to start....LOG:  redirecting log output to logging collector process
HINT:  Future log output will appear in directory "pg_log".
 done
server started
=> sourcing /usr/share/container-scripts/postgresql/start/set_passwords.sh ...
ALTER ROLE
waiting for server to shut down.... done
server stopped
Starting server...
LOG:  redirecting log output to logging collector process
HINT:  Future log output will appear in directory "pg_log".
```
## Environment

* Operating system: Fedora 28
* OpenShift version: 3.10

* Ansible version:

* Project Version/Tag: (E.g release-1.0.1)

**Comment by pmccarthy** [comment] 2018-11-21 15:03
@tremes This is actually an issue with the tooling used to provision POC environments rather than the Integreatly installer. There is a bug where every 3rd request against the master ELB hangs, resulting in timeouts.

The Integreatly SRE team are aware of this problem and are currently looking at implementing a fix. I think this Github issue can be closed out.

**Comment by tremes** [comment] 2018-11-21 15:11
OK then feel free to close it. I am just a QE :-). Is it tracked somewhere?

**Comment by pmccarthy** [comment] 2018-11-21 15:41
@tremes Yes it's currently being tracked in Jira. I didn't add a link as the ticket is not publicly available

**Comment by david-martin** [comment] 2018-11-22 12:00
I'm seeing this on master on PDS.
```
fatal: [127.0.0.1]: FAILED! => {"attempts": 60, "cache_control": "private, max-age=0, no-cache, no-store", "changed": false, "connection": "close", "content": "<html>\n  <head>\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\n  <style type=\"text/css\">\n  /*!\n   * Bootstrap v3.3.5 (http://getbootstrap.com)\n   * Copyright 2011-2015 Twitter, Inc.\n   * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)\n   */\n  /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */\n  html {\n    font-family: sans-serif;\n    -ms-text-size-adjust: 100%;\n    -webkit-text-size-adjust: 100%;\n  }\n  body {\n    margin: 0;\n  }\n  h1 {\n    font-size: 1.7em;\n    font-weight: 400;\n    line-height: 1.3;\n    margin: 0.68em 0;\n  }\n  * {\n    -webkit-box-sizing: border-box;\n    -moz-box-sizing: border-box;\n    box-sizing: border-box;\n  }\n  *:before,\n  *:after {\n    -webkit-box-sizing: border-box;\n    -moz-box-sizing: border-box;\n    box-sizing: border-box;\n  }\n  html {\n    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);\n  }\n  body {\n    font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n    line-height: 1.66666667;\n    font-size: 13px;\n    color: #333333;\n    background-color: #ffffff;\n    margin: 2em 1em;\n  }\n  p {\n    margin: 0 0 10px;\n    font-size: 13px;\n  }\n  .alert.alert-info {\n    padding: 15px;\n    margin-bottom: 20px;\n    border: 1px solid transparent;\n    background-color: #f5f5f5;\n    border-color: #8b8d8f;\n    color: #363636;\n    margin-top: 30px;\n  }\n  .alert p {\n    padding-left: 35px;\n  }\n  a {\n    color: #0088ce;\n  }\n\n  ul {\n    position: relative;\n    padding-left: 51px;\n  }\n  p.info {\n    position: relative;\n    font-size: 15px;\n    margin-bottom: 10px;\n  }\n  p.info:before, p.info:after {\n    content: \"\";\n    position: absolute;\n    top: 9%;\n    left: 0;\n  }\n  p.info:before {\n    content: \"i\";\n    left: 3px;\n    width: 20px;\n    height: 20px;\n    font-family: serif;\n    font-size: 15px;\n    font-weight: bold;\n    line-height: 21px;\n    text-align: center;\n    color: #fff;\n    background: #4d5258;\n    border-radius: 16px;\n  }\n\n  @media (min-width: 768px) {\n    body {\n      margin: 4em 3em;\n    }\n    h1 {\n      font-size: 2.15em;}\n  }\n\n  </style>\n  </head>\n  <body>\n    <div>\n      <h1>Application is not available</h1>\n      <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>\n\n      <div class=\"alert alert-info\">\n        <p class=\"info\">\n          Possible reasons you are seeing this page:\n        </p>\n        <ul>\n          <li>\n            <strong>The host doesn't exist.</strong>\n            Make sure the hostname was typed correctly and that a route matching this hostname exists.\n          </li>\n          <li>\n            <strong>The host exists, but doesn't have a matching path.</strong>\n            Check if the URL path was typed correctly and that the route was created using the desired path.\n          </li>\n          <li>\n            <strong>Route and path matches, but all pods are down.</strong>\n            Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.\n          </li>\n        </ul>\n      </div>\n    </div>\n  </body>\n</html>\n", "content_type": "text/html", "msg": "Status code was 503 and not [200]: HTTP Error 503: Service Unavailable", "pragma": "no-cache", "redirected": false, "status": 503, "url": "https://launcher-sso-launcher.apps.waterford-862c.openshiftworkshop.com/auth/realms/master/protocol/openid-connect/token"}
```

Looks like the url its using is incorrect.
```
https://launcher-sso-launcher.apps.waterford-862c.openshiftworkshop.com/auth/realms/master/protocol/openid-connect/token
```
It's using the non ssl hostname, with https.
Possibly introduced here https://github.com/integr8ly/installation/commit/77d41a3b29392b5835323f7d41e0b3deecb9769c#diff-6de290e3507dbbe68ab781d04bb4995eR99

@philbrookes thoughts on this?

**Comment by pmccarthy** [comment] 2018-11-22 12:14
@tremes Perhaps this isn't related to the timeout issues I was referring to afterall

**Comment by philbrookes** [comment] 2018-11-22 12:36
as I recall the template had stopped adding secure to that start of the secure urls, but it seems to be doing it again now. I'm working on a PR to correct it: https://github.com/integr8ly/installation/pull/188

**Comment by philbrookes** [comment] 2018-11-22 14:07
This is related to an install on a cluster that had an old copy of the template.

**Comment by tremes** [comment] 2018-11-23 15:39
I got the same error installing from master to the new QE cluster - you can see https://integreatly-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/installation-pipeline/92/console

**Comment by camilamacedo86** [comment] 2018-12-03 21:42
@tremes I installed the master branch today by the install.yml playbook and it ends with success.  Please, could you check if you still able to see it and if yes, could you provide the steps to reproduce this issue in the issue description?

**Comment by pawelpaszki** [comment] 2018-12-05 09:59
@tremes I can confirm that I got the same issue twice in a row, while running the installer from the master node

**Comment by philbrookes** [comment] 2018-12-05 10:22
I wonder if there is a difference between the QE clusters template and the template on the PDS cluster?

@tremes Could you take a look at the template for keycloak on your cluster, using this command:
``` oc get template sso72-x509-postgresql-persistent -n openshift -o yaml```

For comparison, here is what I get on a clean PDS cluster:
https://gist.github.com/philbrookes/7b88bbd2ea744c585b14c9d4f2b1cd6a

**Comment by tremes** [comment] 2018-12-05 11:41
@pawelpaszki Thanks Pawel. Can you please  try to compare the template as Phil is suggesting? I don't have RHPDS up and running.

**Comment by pawelpaszki** [comment] 2018-12-05 11:41
@philbrookes here is the output from the command you mentioned 
`oc get template sso72-x509-postgresql-persistent -n openshift -o yaml`

https://gist.github.com/pawelpaszki/3444faf0829ea60f1d2f4b01e1821ff2

**Comment by tremes** [comment] 2018-12-05 11:56
@pawelpaszki Thanks:) @philbrookes Briefly looking and the versions of templates are obviously different. 1.4.11 vs 1.4.14...not sure whether this might be the issue

**Comment by camilamacedo86** [comment] 2018-12-05 15:19
@tremes so, can we close this issue? Is it solve in the latest version for you? If not, could you please provide the steps to reproduce in the first comment?

**Comment by pawelpaszki** [comment] 2018-12-07 10:12
@camilamacedo86 @tremes seems to be working again with the master branch. I can't close this issue because I don't have enough privileges

**Comment by camilamacedo86** [comment] 2018-12-07 10:14
Hi @pawelpaszki ,

Thank you for your feedback. Since it is working I am closing it now.

**Closed by camilamacedo86** 2018-12-07 10:14 UTC
Labels: bug
