### ISSUE TITLE
Unable to open the integr8ly dashboard because issue faced in the enmasse

### ISSUE THREAD

**Issue by camilamacedo86** [integr8ly/installation#226] opened 2018-12-03 22:49 UTC
## Description
Unable to open the integr8ly dashboard because issue faced in the enmasse

## Expected Behavior
Open the dashboard which follows the image

## Actual Behavior

It stay stuck in the 80%. 

<img width="1623" alt="screenshot 2018-12-03 at 22 42 52" src="https://user-images.githubusercontent.com/7708031/49406259-fa142700-f74c-11e8-9f69-d47a0c0bdfcc.png">

 ```json
"spec": {
        "clusterServiceClassExternalName": "enmasse-standard",
        "clusterServicePlanExternalName": "unlimited-standard",
        "parameters": {},
        "externalID": "a03d9ba0-f744-11e8-a882-0a580a010006",
        "userInfo": {
          "username": "admin@example.com",
          "uid": "",
          "groups": [
            "system:authenticated:oauth",
            "system:authenticated"
          ],
          "extra": {
            "scopes.authorization.openshift.io": [
              "user:full"
            ]
          }
        },
        "updateRequests": 0
      },
      "status": {
        "conditions": [
          {
            "type": "Ready",
            "status": "False",
            "lastTransitionTime": "2018-12-03T21:44:35Z",
            "reason": "ReferencesNonexistentServicePlan",
            "message": "The instance references a ClusterServicePlan that does not exist. References a non-existent ClusterServicePlan {PlanExternalName:\"unlimited-standard\"} on ClusterServiceClass c3581d6c-edfd-3989-8d4f-1ac54f26d773 {ClassExternalName:\"enmasse-standard\"} or there is more than one (found: 0)"
          }
        ],
        "asyncOpInProgress": false,
        "orphanMitigationInProgress": false,
        "reconciledGeneration": 0,
        "observedGeneration": 1,
        "provisionStatus": "",
        "deprovisionStatus": "NotRequired"
      }
    },
```
<img width="1405" alt="screenshot 2018-12-03 at 22 53 30" src="https://user-images.githubusercontent.com/7708031/49406726-4b70e600-f74e-11e8-996c-34d74098483e.png">

## Environment

* Operating system: RHDSY
* OpenShift version:
```shell
oc version
oc v3.10.14
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://master1.london-7948.internal:443
openshift v3.10.14
kubernetes v1.10.0+b81c8f8
[root@bastion evals]# 
```
* Ansible version:

```shell
[root@bastion evals]# ansible --version
ansible 2.4.6.0
  config file = /root/installation/evals/ansible.cfg
  configured module search path = [u'/root/installation/evals/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
[root@bastion evals]# 
```
* Project Version/Tag: master at 03/12/2018

## Steps to reproduce
1. Create an OCP instance by RHDSY. See [here](https://github.com/integr8ly/installation#using-red-hat-product-demo-system-to-have-an-openshift-instance-valid-just-for-partners-and-redhatters)
2. Run the installation with the launcher.  `ansible-playbook -i inventories/hosts playbooks/install.yml -e github_client_id=xxx -e github_client_secret=xxx`
3. Go to the GitHub account and update the URL of the Oauth. See [here](https://github.com/integr8ly/installation#1-create-github-oauth-to-enable-github-authorization-for-launcher)
4. Login into the OpenShift with the admin user
5. Go to the webapp project
6. Go to routers tab and click on it in order to try test it

**Comment by camilamacedo86** [comment] 2018-12-03 22:51
Hi folks,

It shows a critical bug. 

c/c @maleck13 @tremes @philbrookes

**Comment by trepel** [comment] 2018-12-04 07:40
I can confirm that I came across this as well on my PDS cluster. Openshift 3.11, plain OpenShift workshop, installation from master branch.

**Comment by maleck13** [comment] 2018-12-04 08:46
ping @david-martin this might be something that needs to be changed in the webapp?

**Comment by david-martin** [comment] 2018-12-04 09:45
@maleck13 I agree.
The error part looks like something the webapp should be able to parse in a deterministic way, and present to the user so they can remedy it.

@camilamacedo86 would mind creating on https://github.com/integr8ly/tutorial-web-app repo?
This falls nicely into a card on our backlog related to improving this screen

**Comment by david-martin** [comment] 2018-12-04 10:02
@trepel @camilamacedo86 Can you verify the image tag for the webapp in your clusters is that of the `master` tag i.e. 4cc0ce59cffe
https://quay.io/repository/integreatly/tutorial-web-app?tab=tags

**Comment by david-martin** [comment] 2018-12-04 10:11
https://github.com/integr8ly/tutorial-web-app-operator/pull/12

**Comment by camilamacedo86** [comment] 2018-12-04 10:18
Hi @david-martin since it still not fixed I will re-open the issue and I will try to do the test with the image generated in the PR https://github.com/integr8ly/tutorial-web-app-operator/pull/12. Should I update the install playbook in order to get this image? Am I right? Could you just tell where?

**Comment by david-martin** [comment] 2018-12-04 10:20
@camilamacedo86 `Can you verify the image tag for the webapp in your clusters is that of the master tag i.e. 4cc0ce59cffe`

**Comment by trepel** [comment] 2018-12-04 10:40
@david-martin hmm, it seems there is '1.0.0' tag on my cluster. I'll try to investigate how thats' possible

**Comment by camilamacedo86** [comment] 2018-12-04 10:49
Hi @trepel.

Shows that the playbook to install is using the tag 1.0.0. See it [here](https://github.com/integr8ly/installation/blob/master/evals/roles/webapp/defaults/main.yml#L8). Is this the problem @david-martin ? Should it be taken the master tag? So, to solve this issue I understand that we need update the install project at this point, I mean to revert the PR https://github.com/integr8ly/installation/commit/cacb2a6366720701d28ac7ae2b3c3e2d2440f046#diff-a725aea3306b6167ba1b69d091ca4f04

**Comment by david-martin** [comment] 2018-12-04 10:56
@camilamacedo86 @trepel Some questions:

* what branch or tag of the installation repo were you running from?
* how long has your cluster running for?
* how many installs have been run against that cluster?

**Comment by camilamacedo86** [comment] 2018-12-04 11:19
Hi @david-martin, following the answers. 

* we are using the playbook install.yml of the master branch this project 
* The master branch of this project has the tag 1.0.0 fixed as you can check [here](https://github.com/integr8ly/installation/blob/master/evals/roles/webapp/defaults/main.yml#L8)
* in the PR https://github.com/integr8ly/installation/commit/cacb2a6366720701d28ac7ae2b3c3e2d2440f046#diff-a725aea3306b6167ba1b69d091ca4f04 it was changed/replaced from master to the tag 1.0.0
* After the installation, I wait more than one hour definitely 
* The tag 1.0.0 of webapp with the master installation is facing the issue `The instance references a ClusterServicePlan that does not exist. References a non-existent ClusterServicePlan {PlanExternalName:\"unlimited-standard\"} on ClusterServiceClass c3581d6c-edfd-3989-8d4f-1ac54f26d773 {ClassExternalName:\"enmasse-standard\"} or there is more than one (found: 0)"` where it get stuck on the 80% and the dashboard never will be opened. 

Following some questions.

1. Is the fix for this issue the PR https://github.com/integr8ly/tutorial-web-app-operator/pull/12?
2. If yes, how can we update the install project to use the image generated from the PR https://github.com/integr8ly/tutorial-web-app-operator/pull/12? 
3. Should I see and should I found the images indeed of this above PR in the link https://quay.io/repository/integreatly/tutorial-web-app?tab=tags\? If yes, could you give me this permission? 
4. What tag should the installation in the master branch be using? Should it be fixed 1.0.0? Should not better we work with the last tag build for production? For example, instead of having fixed a number which will be required be updated always should not easier we build release tags and the install always get the latest released tag of someone component?

**Comment by david-martin** [comment] 2018-12-04 11:56
> * Is the fix for this issue the PR [integr8ly/tutorial-web-app-operator#12](https://github.com/integr8ly/tutorial-web-app-operator/pull/12)?

Not quite, that is to ensure by default the latest version of the tag is used.


> * Should I see and should I found the images indeed of this above PR in the link [https://quay.io/repository/integreatly/tutorial-web-app?tab=tags\](https://quay.io/repository/integreatly/tutorial-web-app?tab=tags%5C)? If yes, could you give me this permission?

Was an incorrect url. Should be https://quay.io/repository/integreatly/tutorial-web-app?tab=tags

> 4\. What tag should the installation in the master branch be using

`master`. It gets updated at release time on a release branch

**Comment by david-martin** [comment] 2018-12-04 11:56
@odra In the webapp operator, is the webapp image to use hardcoded or configurable for the CR?

**Comment by odra** [comment] 2018-12-04 12:00
it is set in the CR:
https://github.com/integr8ly/installation/blob/master/evals/roles/webapp/templates/cr.yaml.j2#L12

**Comment by david-martin** [comment] 2018-12-04 12:05
Thanks @odra .

@camilamacedo86 @trepel so the fix here would be to change the default in this repo to `master` if you want to try that?

**Comment by trepel** [comment] 2018-12-04 12:10
Thanks, I will give it a try.

**Comment by tremes** [comment] 2018-12-05 15:45
@david-martin Well so I tried to install with master tags (using Mike's branch https://github.com/integr8ly/installation/pull/236) and the webapp is still not able to load. 

I think the problem is in service instances which are pending  due to `References a non-existent ClusterServiceClass {ClusterServiceClassExternalName:"apicurio"} or there is more than one (found: 0)`

**Comment by camilamacedo86** [comment] 2018-12-05 15:53
@tremes so the issue changed, now shows be another image which is no loading. I will test it now again with the master branch and the master branches.

**Comment by pawelpaszki** [comment] 2018-12-07 12:03
@david-martin @tremes I have ran the installer with the master (about two hours ago) and it worked, e.g. the walkthrough loaded correctly

**Comment by tremes** [comment] 2018-12-07 12:10
@pawelpaszki OK thanks. Now it's working for me as well on Pony cluster so closing.

**Closed by tremes** 2018-12-07 12:10 UTC
Labels: Enmasse, bug, help wanted, p1
